### ISSUE TITLE
app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by skater19** [jadsalhani/ionic2-qrscanner-example#1]
Hello, i followed the steps you wrote, when opening the app on my mobile, i get white screen. After ionic serving on my desktop, i get the error from the title:

http://localhost:8100/build/js/app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by jadsalhani** [comment]
Hi @skater19, The steps on the repo are now outdated (since Ionic RC4 is released now). But seeing that some people are still using it, I'll update it today to the latest version and ping you when it done!

**Comment by jadsalhani** [comment]
@skater19 I suggest you try, please follow the steps again for a clean install and let me know how it goes
