### ISSUE TITLE
Scan result page is blank

### ISSUE THREAD

**Issue by robrecht-vanmelckebeke** [jadsalhani/ionic2-qrscanner-example#2]
Hi,

First of all thank you for your example for a QR scanner in ionic 2 !
The scanning seems to work fine; as soon as I scan a QR code the app sends me to the test result page.
But this page is blank.
I will try to take a look at the code and post the solution but maybe you have seen this before and you can save me some time?

Many thanks

**Comment by jadsalhani** [comment]
Hi @robrecht-vanmelckebeke !

I'm glad you like the example :D 

Regarding the scan result being blank, mainly the page only displays the scanned text returned by the QR code (if it is returned).
Can you console log the `barcodeData` object returned by the QR code and check the contents? If it doesn't contain the "scannedText" property then it won't show up on the next page.

Let me know!

**Comment by robrecht-vanmelckebeke** [comment]
Hi,

Problem is that I don't know how to console log stuff coming from the iphone camera.
I could try it in browser but I guess I can't scan a QR code through my laptop webcam and log the scanned result ?

**Comment by jadsalhani** [comment]
What you can do is plug your iphone to your laptop (I'm assuming you're working on a mac since you can build for iphone?) and run it from XCode to your iphone. 

When the app starts open Safari -> Develop tab -> you should see you iphone name, hover over and the app name should pop up with index.html 

this [link](https://webdesign.tutsplus.com/articles/quick-tip-using-web-inspector-to-debug-mobile-safari--webdesign-8787) could help setup debugging with Safari if the above steps don't show up.

After that you can just open the console and log any output you want from the Device

**Comment by robrecht-vanmelckebeke** [comment]
Hi,

Thanks for the info!
In safari console I logged barcodeData which contains : 

`[Log] {cancelled: 0, text: "", format: "QR_CODE"} (console-via-logger.js, line 173)`

So no "scannedText" property and "text" property is blank...

**Comment by jadsalhani** [comment]
Then you should use your `text` property :)

Anyway, there must be something wrong with the QR code since the `text` property is empty anyway.

Glad I could help! Going to close this

**Comment by robrecht-vanmelckebeke** [comment]
Hi,

I don't think sth is wrong with the barcode...
I found several issues regarding the text property being empty.. 
Some solutions suggest to use on-touch instead of ng-click to avoid scanning twice...

I'll try that

Robrecht

**Comment by jadsalhani** [comment]
Hi @robrecht-vanmelckebeke 

Does the scanner pop up twice? There's no reason the button would be tapped twice with the `(click)`. If it does open twice let me know

Usually when the `text` field is empty it means the QR doesn't hold any data. Did you try any other QR reader to check if the correct data is displayed? Maybe the Chrome one on iOS or any other QR reader.

**Comment by robrecht-vanmelckebeke** [comment]
Omg, you are right, my QR code doesn't contain any data..
Scanning another code (and printing "text" property instead of "scannedText") did the job
Many many thanks for your help and your time !!
