### ISSUE TITLE
Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

### ISSUE THREAD

**Issue by tayzee** [jadsalhani/ionic2-qrscanner-example#3]
Hi There, 

I am getting this error when trying to use your example.

I however have the latest version of Cordova installed (globally) - 6.5.0

Any way I can fix this?

**Comment by jadsalhani** [comment]
Hello,

Try re-installing cordova and ionic, maybe that'll fix it
Other than that the issue is most probably related with your Cordova installation
